CREATE TABLE clientes (
  CPF varchar(11) NOT NULL,
  NOME varchar(100) DEFAULT NULL,
  ENDERECO varchar(150) DEFAULT NULL,
  BAIRRO varchar(50) DEFAULT NULL,
  CIDADE varchar(50) DEFAULT NULL,
  ESTADO varchar(45) DEFAULT NULL,
  CEP varchar(8) DEFAULT NULL,
  DATA_NASCIMENTO date DEFAULT NULL,
  IDADE int(11) DEFAULT NULL,
  SEXO varchar(1) DEFAULT NULL,
  LIMITE_CREDITO float DEFAULT NULL,
  VOLUME_COMPRA float DEFAULT NULL,
  PRIMEIRA_COMPRA bit(1) DEFAULT NULL,
  PRIMARY KEY (CPF)
)
